variables:
  TZ: "Asia/Shanghai"
  MAVEN_CLI_OPTS: " --batch-mode -Dorg.slf4j.simpleLogger.defaultLogLevel=warn"


stages:
  - testOnJava17
  - sonarOnJava17
  - deploy


testOnJava17:
  image: maven:3.8.3-eclipse-temurin-17
  stage: testOnJava17
  script:
    - keytool -keystore $JAVA_HOME/lib/security/cacerts -storepass changeit -noprompt -trustcacerts -importcert -alias guanaitongca -file .gitlab/GuanaitongCA.crt
    - mvn $MAVEN_CLI_OPTS test -Djava.version=17 -Djacoco.skip=true

sonarOnJava17:
  image: maven:3.8.3-eclipse-temurin-17
  stage: sonarOnJava11
  script:
    - keytool -keystore $JAVA_HOME/lib/security/cacerts -storepass changeit -noprompt -trustcacerts -importcert -alias guanaitongca -file .gitlab/GuanaitongCA.crt
    - mvn $MAVEN_CLI_OPTS package sonar:sonar -Dsonar.projectKey=grus-2 -Dsonar.projectName=grus-2 -Djacoco.skip=false


deploy:
  image: maven:3.8.3-eclipse-temurin-17
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy -Dmaven.test.skip=true
    - sh generate_parent_pom.sh
    - mvn $MAVEN_CLI_OPTS -f tmp/.flattened-pom.xml -Dmaven.test.skip=true deploy
  only:
    - master
    - 2021.1.x
